server:
  port: 8000


spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    view:
      prefix: /
      suffix: .html
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

#  flyway:
#    enabled: true
#    baseline-on-migrate: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://0.0.0.0:5432/postgres
    username: "tester"
    password: "sa"


#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#  sql:
#    init:
#      mode: always


#springdoc:
#  api-docs:
#    path: /api-docs
#  show-actuator: true
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  writer-with-default-pretty-printer: true
#  model-and-view-allowed: true
#  paths-to-match:
#
#  swagger-ui:
#    path: /swagger-ui.html
#    configUrl: /v3/api-docs/swagger-config
#    layout: BaseLayout
#    groups-order: DESC
#    tags-sorter: alpha
#    operations-sorter: alpha
#    disable-swagger-default-url: true
#    display-request-duration: true
#    defaultModelsExpandDepth: 2
#    defaultModelExpandDepth: 2

