### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8000/api/post-obj
{
  "user": "dd",
  "email": "d@dd.d",
  "pw" : "890"
}
